CREATE TABLE IF NOT EXISTS `operation_log` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NOT NULL,
  `username` VARCHAR(64) NOT NULL,
  `action` VARCHAR(64) NOT NULL,
  `target` VARCHAR(64) NOT NULL,
  `target_id` BIGINT DEFAULT NULL,
  `detail` TEXT DEFAULT NULL,
  `ip` VARCHAR(45) DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `notice` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NOT NULL,
  `type` VARCHAR(32) NOT NULL DEFAULT 'info',
  `status` TINYINT NOT NULL DEFAULT 0,
  `priority` TINYINT NOT NULL DEFAULT 0,
  `author_id` BIGINT NOT NULL,
  `author_name` VARCHAR(64) NOT NULL,
  `publish_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `inventory` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `category` VARCHAR(64) DEFAULT NULL,
  `quantity` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `unit` VARCHAR(32) NOT NULL,
  `threshold` DECIMAL(10,2) DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  `last_restock_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `recipe_review` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `recipe_id` BIGINT NOT NULL,
  `recipe_name` VARCHAR(200) NOT NULL,
  `reviewer_id` BIGINT NOT NULL,
  `reviewer_name` VARCHAR(64) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  `comment` TEXT DEFAULT NULL,
  `review_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `system_health` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `metric_name` VARCHAR(64) NOT NULL,
  `metric_value` VARCHAR(200) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'ok',
  `description` TEXT DEFAULT NULL,
  `check_time` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
