SET NAMES utf8mb4;

-- Add nutrition fields to recipe table
ALTER TABLE recipe ADD COLUMN IF NOT EXISTS calories DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE recipe ADD COLUMN IF NOT EXISTS protein DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE recipe ADD COLUMN IF NOT EXISTS fat DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE recipe ADD COLUMN IF NOT EXISTS carbs DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE recipe ADD COLUMN IF NOT EXISTS fiber DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE recipe ADD COLUMN IF NOT EXISTS cost DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE recipe ADD COLUMN IF NOT EXISTS selling_price DECIMAL(10,2) DEFAULT NULL;

-- Recipe favorites
CREATE TABLE IF NOT EXISTS recipe_favorite (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  recipe_id BIGINT NOT NULL,
  recipe_name VARCHAR(200) DEFAULT NULL,
  recipe_cover VARCHAR(500) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Recipe comments
CREATE TABLE IF NOT EXISTS recipe_comment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  recipe_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  username VARCHAR(64) NOT NULL,
  nickname VARCHAR(64) DEFAULT NULL,
  avatar VARCHAR(500) DEFAULT NULL,
  content TEXT NOT NULL,
  rating TINYINT DEFAULT 5,
  parent_id BIGINT DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Recipe versions
CREATE TABLE IF NOT EXISTS recipe_version (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  recipe_id BIGINT NOT NULL,
  version INT NOT NULL,
  name VARCHAR(200) DEFAULT NULL,
  cover VARCHAR(500) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  difficulty VARCHAR(20) DEFAULT NULL,
  cooking_time INT DEFAULT NULL,
  materials_json TEXT DEFAULT NULL,
  steps_json TEXT DEFAULT NULL,
  change_note VARCHAR(500) DEFAULT NULL,
  operator_id BIGINT DEFAULT NULL,
  operator_name VARCHAR(64) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Suppliers
CREATE TABLE IF NOT EXISTS supplier (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  contact VARCHAR(64) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  address VARCHAR(300) DEFAULT NULL,
  category VARCHAR(64) DEFAULT NULL,
  rating TINYINT DEFAULT 5,
  status TINYINT NOT NULL DEFAULT 1,
  remark TEXT DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Meal plans
CREATE TABLE IF NOT EXISTS meal_plan (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  plan_date DATE NOT NULL,
  meal_type VARCHAR(20) NOT NULL,
  recipe_id BIGINT DEFAULT NULL,
  recipe_name VARCHAR(200) DEFAULT NULL,
  recipe_cover VARCHAR(500) DEFAULT NULL,
  servings INT DEFAULT 1,
  note VARCHAR(500) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Shopping items
CREATE TABLE IF NOT EXISTS shopping_item (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  list_name VARCHAR(100) DEFAULT '默认清单',
  ingredient_name VARCHAR(100) NOT NULL,
  quantity DECIMAL(10,2) DEFAULT 0,
  unit VARCHAR(32) DEFAULT NULL,
  category VARCHAR(64) DEFAULT NULL,
  is_checked TINYINT DEFAULT 0,
  source_recipe_id BIGINT DEFAULT NULL,
  source_recipe_name VARCHAR(200) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
