CREATE TABLE IF NOT EXISTS ai_chat_session (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL DEFAULT '新对话',
  provider VARCHAR(50),
  model VARCHAR(100),
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ai_chat_message (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  session_id BIGINT NOT NULL,
  role VARCHAR(20) NOT NULL,
  content MEDIUMTEXT NOT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted INT DEFAULT 0,
  INDEX idx_session_id (session_id)
);
