import request from '@/utils/request'

export const aiChat = (data: any) => request.post('/ai/chat', data)
export const aiRecommend = (userId?: string) => request.get('/ai/recommend', { params: { userId } })
export const aiIngredientToRecipe = (data: any) => request.post('/ai/ingredient-to-recipe', data)
export const aiNutrition = (data: any) => request.post('/ai/nutrition', data)
export const aiMealPlan = (data: any) => request.post('/ai/meal-plan', data)
export const aiRecognize = (data: any) => request.post('/ai/recognize', data)
export const aiShoppingList = (data: any) => request.post('/ai/shopping-list', data)
export const aiLeftover = (data: any) => request.post('/ai/leftover', data)
export const aiScore = (data: any) => request.post('/ai/score', data)
export const aiCookingQA = (data: any) => request.post('/ai/cooking-qa', data)
export const aiHealthReport = (userId?: string) => request.get('/ai/health-report', { params: { userId } })
export const aiTranslate = (data: any) => request.post('/ai/translate', data)
export const aiInfo = () => request.get('/ai/info')
export const aiGetConfig = () => request.get('/ai/config')
export const aiUpdateConfig = (data: any) => request.post('/ai/config', data)
export const aiTestConnection = () => request.post('/ai/test')

export const aiListSessions = () => request.get('/ai/sessions')
export const aiCreateSession = (data?: { title?: string }) => request.post('/ai/sessions', data || {})
export const aiDeleteSession = (id: number) => request.delete(`/ai/sessions/${id}`)
export const aiListMessages = (sessionId: number) => request.get(`/ai/sessions/${sessionId}/messages`)
export const aiChatSession = (data: { sessionId?: number; message: string }) => request.post('/ai/chat-session', data)
